version: '3.8'
services:
  php:
    build: ./POS-API
    container_name: pos_php
    ports:
      - "8000:80"
    volumes:
      - ./POS-API:/var/www/html
    depends_on:
      - db
  react:
    build: ./alsaeidi-drink
    container_name: pos_react
    ports:
      - "3000:8080"
    volumes:
      - ./alsaeidi-drink:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    image: mysql:8.0
    container_name: pos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pos_db
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin_POS:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_POS
    restart: unless-stopped
    ports:
        - "9090:80"
    environment:
        PMA_HOST: db
        # PMA_USER: snossy
        # PMA_PASSWORD: 123
    depends_on:
        - db
    
volumes:
  db_data:
